services:
  app:
    build:
      context: .
    ports:
      - '${APP_PORT}:8080'
    environment:
      - NODE_ENV='${NODE_ENV}'
    volumes:
      - './:/usr/src/app'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    ports:
      - '${DB_PORT}:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql: